/**
 * ManageSpace Billing API
 * ManageSpace Billing API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type AccountTransactionType = 'charge' | 'fee' | 'payment' | 'refund' | 'waive';

export const AccountTransactionType = {
    Charge: 'charge' as AccountTransactionType,
    Fee: 'fee' as AccountTransactionType,
    Payment: 'payment' as AccountTransactionType,
    Refund: 'refund' as AccountTransactionType,
    Waive: 'waive' as AccountTransactionType
};

