/**
 * ManageSpace Billing API
 * ManageSpace Billing API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreditDistribution } from './creditDistribution';


export interface ApplyCredit { 
    /**
     * Credit distributions
     */
    creditDistributions: Array<CreditDistribution>;
    /**
     * Action to apply credit.
     */
    action: ApplyCredit.ActionEnum;
}
export namespace ApplyCredit {
    export type ActionEnum = 'WAIVE_FEE' | 'ADD_FEE' | 'APPLY_CREDIT';
    export const ActionEnum = {
        WaiveFee: 'WAIVE_FEE' as ActionEnum,
        AddFee: 'ADD_FEE' as ActionEnum,
        ApplyCredit: 'APPLY_CREDIT' as ActionEnum
    };
}


