/**
 * ManageSpace Billing API
 * ManageSpace Billing API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type EBillingCycleTypeEnum = 'FIRST_OF_MONTH' | 'END_OF_MONTH' | 'ANNIVERSARY_30' | 'ANNIVERSARY_31' | 'FOUR_WEEK_CYCLE';

export const EBillingCycleTypeEnum = {
    FirstOfMonth: 'FIRST_OF_MONTH' as EBillingCycleTypeEnum,
    EndOfMonth: 'END_OF_MONTH' as EBillingCycleTypeEnum,
    Anniversary30: 'ANNIVERSARY_30' as EBillingCycleTypeEnum,
    Anniversary31: 'ANNIVERSARY_31' as EBillingCycleTypeEnum,
    FourWeekCycle: 'FOUR_WEEK_CYCLE' as EBillingCycleTypeEnum
};

