/**
 * ManageSpace Billing API
 * ManageSpace Billing API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type EInvoicePeriodType = 'monthly' | 'quarterly' | 'bi-weekly';

export const EInvoicePeriodType = {
    Monthly: 'monthly' as EInvoicePeriodType,
    Quarterly: 'quarterly' as EInvoicePeriodType,
    BiWeekly: 'bi-weekly' as EInvoicePeriodType
};

