/**
 * ManageSpace Billing API
 * ManageSpace Billing API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccountCurrentBalance } from './accountCurrentBalance';


export interface GetAccountCurrentBalance200Response { 
    data?: Array<AccountCurrentBalance>;
    success?: boolean;
    error?: object;
}

