/**
 * ManageSpace Billing API
 * ManageSpace Billing API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Address of the account associated with the invoice.
 */
export interface InvoiceV2ResponseAddress { 
    /**
     * Invoice Address ID.
     */
    invoiceAddressId: string;
    /**
     * First line of the address.
     */
    addressLineOne: string;
    /**
     * Second line of the address.
     */
    addressLineTwo: string | null;
    /**
     * City the address is in.
     */
    city: string;
    /**
     * State/Province the address is in.
     */
    province: string;
    /**
     * Post code of the address.
     */
    postalCode: string;
    /**
     * Country the address is in.
     */
    country: string;
}

