/**
 * ManageSpace Billing API
 * ManageSpace Billing API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Invoice ID and status
 */
export interface InvoiceV2LineItemResponseInvoice { 
    invoiceId?: string;
    invoiceStatus?: InvoiceV2LineItemResponseInvoice.InvoiceStatusEnum;
}
export namespace InvoiceV2LineItemResponseInvoice {
    export type InvoiceStatusEnum = 'paid' | 'unpaid' | 'overdue';
    export const InvoiceStatusEnum = {
        Paid: 'paid' as InvoiceStatusEnum,
        Unpaid: 'unpaid' as InvoiceStatusEnum,
        Overdue: 'overdue' as InvoiceStatusEnum
    };
}


