/**
 * ManageSpace Billing API
 * ManageSpace Billing API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface InvoiceLineItemResponse { 
    /**
     * Line Item ID.
     */
    invoiceLineItemId: string;
    /**
     * Unit id.
     */
    unitId?: string;
    /**
     * Product id.
     */
    productId?: string;
    /**
     * Refers to either unitName or productName.
     */
    name: string;
    /**
     * Description
     */
    description: string;
    /**
     * Quantity
     */
    quantity?: number;
    /**
     * The recurring monthly rate in the smallest currency unit (e.g. cents for USD) or the one-time price (if product).
     */
    price: number;
}

