/**
 * ManageSpace Billing API
 * ManageSpace Billing API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EInvoicePeriodType } from './eInvoicePeriodType';
import { EBillingCycleTypeEnum } from './eBillingCycleTypeEnum';


export interface InvoiceRunResponse { 
    /**
     * Invoice run ID
     */
    invoiceRunId: string;
    /**
     * Org ID
     */
    orgId: string;
    invoicePeriodType: EInvoicePeriodType;
    billingCycleType: EBillingCycleTypeEnum;
    /**
     * Invoice period start date
     */
    invoicePeriodStartDate: string;
    /**
     * Invoice period end date
     */
    invoicePeriodEndDate: string;
    /**
     * Created at
     */
    createdAt: string;
    /**
     * Created by
     */
    createdBy: string;
    /**
     * Success.
     */
    successful: boolean;
    /**
     * Error
     */
    error: boolean;
}
export namespace InvoiceRunResponse {
}


