/**
 * ManageSpace Billing API
 * ManageSpace Billing API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FeeDetails } from './feeDetails';
import { CreditDistribution } from './creditDistribution';
import { WaiveFee } from './waiveFee';
import { ApplyCredit } from './applyCredit';
import { AddFee } from './addFee';


/**
 * Action payload
 */
/**
 * @type InvoiceLineItemActionRequestPayload
 * Action payload
 * @export
 */
export type InvoiceLineItemActionRequestPayload = AddFee | ApplyCredit | WaiveFee;

