/**
 * ManageSpace Billing API
 * ManageSpace Billing API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InvoiceV2ResponseAddress } from './invoiceV2ResponseAddress';
import { InvoiceStatus } from './invoiceStatus';
import { ReducedInvoiceV2LineItem } from './reducedInvoiceV2LineItem';


export interface InvoiceV2Response { 
    /**
     * Invoice ID.
     */
    invoiceId: string;
    /**
     * Sequential Invoice Number.
     */
    invoiceNumber: number;
    /**
     * Account id.
     */
    accountId: string;
    /**
     * Email
     */
    email: string;
    /**
     * Mobile phone number
     */
    mobileNumber: string;
    /**
     * Org id.
     */
    orgId: string;
    /**
     * Account id.
     */
    siteId: string;
    /**
     * Account Name.
     */
    accountName: string;
    /**
     * Total amount for all line items in smallest currency unit (e.g. cents for USD).
     */
    totalAmount: number;
    address: InvoiceV2ResponseAddress | null;
    /**
     * Invoice line items.
     */
    invoiceLineItems: Array<ReducedInvoiceV2LineItem>;
    invoiceStatus: InvoiceStatus;
    /**
     * Created at.
     */
    createdAt: string;
    /**
     * Updated at.
     */
    updatedAt: string;
    /**
     * Invoice period start date.
     */
    invoicePeriodStartDate: string | null;
    /**
     * Invoice period end date.
     */
    invoicePeriodEndDate: string | null;
    /**
     * Unpaid invoice line items
     */
    unpaid: Array<string> | null;
}
export namespace InvoiceV2Response {
}


