/**
 * ManageSpace Billing API
 * ManageSpace Billing API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Invoice ID and status
 */
export interface InvoiceV2LineItemResponseInvoice { 
    invoiceId?: string;
    invoiceStatus?: InvoiceV2LineItemResponseInvoice.InvoiceStatusEnum;
}
export namespace InvoiceV2LineItemResponseInvoice {
    export type InvoiceStatusEnum = 'due' | 'paid' | 'pending' | 'unpaid' | 'draft' | 'overdue';
    export const InvoiceStatusEnum = {
        Due: 'due' as InvoiceStatusEnum,
        Paid: 'paid' as InvoiceStatusEnum,
        Pending: 'pending' as InvoiceStatusEnum,
        Unpaid: 'unpaid' as InvoiceStatusEnum,
        Draft: 'draft' as InvoiceStatusEnum,
        Overdue: 'overdue' as InvoiceStatusEnum
    };
}


