/**
 * ManageSpace Billing API
 * ManageSpace Billing API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface InvoiceLineItemAdjustmentResponse { 
    /**
     * Adjustment ID
     */
    invoiceLineItemAdjustmentId: string;
    /**
     * Invoice Line Item ID
     */
    invoiceLineItemId: string;
    /**
     * Adjustment amount
     */
    amount: number;
    /**
     * Description.
     */
    description: string | null;
    /**
     * Created by
     */
    createdBy: string;
}

