/**
 * ManageSpace Billing API
 * ManageSpace Billing API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EBillingCycleTypeEnum } from './eBillingCycleTypeEnum';


export interface InvoiceRunRequest { 
    billingCycleType: EBillingCycleTypeEnum;
    /**
     * Valid IANA specific zone; UTC is also supported as a value.
     */
    timezone: string;
    /**
     * Overrides current date.
     */
    currentDateOverride?: string;
}
export namespace InvoiceRunRequest {
}


