/**
 * ManageSpace Billing API
 * ManageSpace Billing API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InvoiceResponseAddress } from './invoiceResponseAddress';
import { InvoiceLineItemResponse } from './invoiceLineItemResponse';


export interface InvoiceResponse { 
    /**
     * Invoice ID.
     */
    invoiceId: string;
    /**
     * Account id.
     */
    accountId: string;
    /**
     * Email
     */
    email: string;
    /**
     * Mobile phone number
     */
    mobileNumber: string;
    /**
     * Org id.
     */
    orgId: string;
    /**
     * Account Name.
     */
    accountName: string;
    /**
     * Transaction id.
     */
    transactionId: string;
    /**
     * The transaction date.
     */
    transactionDate: string;
    /**
     * Transaction status.
     */
    transactionStatus: string;
    /**
     * Payment provider invoice id.
     */
    paymentProviderInvoiceId: string;
    /**
     * Payment provider invoice status.
     */
    paymentProviderStatus: string;
    /**
     * Account id.
     */
    siteId: string;
    /**
     * The currency.
     */
    currency: string;
    /**
     * Total amount for all line items in smallest currency unit (e.g. cents for USD).
     */
    totalAmount: number;
    address: InvoiceResponseAddress | null;
    /**
     * Created at.
     */
    createdAt: string;
    /**
     * Updated at.
     */
    updatedAt: string;
    /**
     * Invoice line items.
     */
    invoiceLineItems: Array<InvoiceLineItemResponse>;
}

