/**
 * ManageSpace Billing API
 * ManageSpace Billing API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type InvoiceStatus = 'paid' | 'unpaid' | 'overdue';

export const InvoiceStatus = {
    Paid: 'paid' as InvoiceStatus,
    Unpaid: 'unpaid' as InvoiceStatus,
    Overdue: 'overdue' as InvoiceStatus
};

