/**
 * ManageSpace Billing API
 * ManageSpace Billing API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InvoiceV2LineItemResponseInvoice } from './invoiceV2LineItemResponseInvoice';


export interface InvoiceV2LineItemResponse { 
    /**
     * Line Item ID.
     */
    invoiceLineItemId: string;
    /**
     * Site ID
     */
    siteId: string;
    /**
     * Org ID
     */
    orgId: string;
    /**
     * Account ID
     */
    accountId: string;
    /**
     * Description
     */
    description: string | null;
    /**
     * Quantity
     */
    quantity: number | null;
    /**
     * The recurring monthly rate in the smallest currency unit (e.g. cents for USD) or the one-time price (if product).
     */
    unitPrice: number;
    /**
     * Product ID
     */
    productId: string | null;
    /**
     * Rental ID
     */
    rentalId: string | null;
    /**
     * Fee ID
     */
    feeId: string | null;
    /**
     * Ledger ID
     */
    ledgerId: string | null;
    /**
     * Tag.
     */
    tag: string;
    invoice: InvoiceV2LineItemResponseInvoice | null;
}

