/**
 * ManageSpace Billing API
 * ManageSpace Billing API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TransactionSummaryResponse } from './transactionSummaryResponse';


export interface LedgerDetailsResponse { 
    /**
     * The Ledger ID
     */
    ledgerId: string;
    /**
     * The Organization ID
     */
    orgId: string;
    /**
     * The site ID
     */
    siteId: string;
    /**
     * The unit ID
     */
    unitId: string;
    /**
     * The rental ID
     */
    rentalId: string;
    /**
     * Start date of the rental.
     */
    periodStart: string;
    /**
     * End date of the rental.
     */
    periodEnd: string | null;
    /**
     * Ledger balance.
     */
    balance: number;
    /**
     * Ledger Amount due
     */
    totalDue: number;
    /**
     * Ledger Amount paid.
     */
    totalPaid: number;
    /**
     * Account Name
     */
    accountName: string;
    /**
     * Email
     */
    email: string | null;
    /**
     * Mobile Number
     */
    mobileNumber: string;
    /**
     * Account ID
     */
    accountId: string;
    /**
     * Transaction Summary.
     */
    transactionsSummary: Array<TransactionSummaryResponse>;
}

