/**
 * ManageSpace Billing API
 * ManageSpace Billing API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface WaiveFee { 
    /**
     * ID of the invoice line item to waive
     */
    invoiceLineItemId: string;
    /**
     * Action to waive fee
     */
    action: WaiveFee.ActionEnum;
}
export namespace WaiveFee {
    export type ActionEnum = 'WAIVE_FEE' | 'ADD_FEE' | 'APPLY_CREDIT';
    export const ActionEnum = {
        WaiveFee: 'WAIVE_FEE' as ActionEnum,
        AddFee: 'ADD_FEE' as ActionEnum,
        ApplyCredit: 'APPLY_CREDIT' as ActionEnum
    };
}


